Repository SOPT-all/35-APPJAM-SERVER-JEOLLOGA, pull requests merged in 2025-01, with the labels that each got.

#7 Feat/#1 issue crawling
  data/crawling/ReviewImgUrlCrawling.py
  data/dataprocessing/TemplestayFilterNameInsert
Labels: feat

#9 Feat/#issue review
  build.gradle
  src/main/java/sopt/jeolloga/common/DataUtils.java
  src/main/java/sopt/jeolloga/common/ResponseDto.java
  src/main/java/sopt/jeolloga/config/BatchConfig.java
  src/main/java/sopt/jeolloga/config/SecurityConfig.java
  src/main/java/sopt/jeolloga/domain/templestay/TemplestayBaseException.java
  src/main/java/sopt/jeolloga/domain/templestay/api/GlobalExceptionHandler.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/ReviewApiController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/Reviewcontroller.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/ReviewApiDto.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/ReviewDto.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/ReviewApiService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/ReviewService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/vo/ImageItemVO.java
  src/main/java/sopt/jeolloga/domain/templestay/api/vo/ImageSearchResultVO.java
  src/main/java/sopt/jeolloga/domain/templestay/api/vo/NaverResultVO.java
  src/main/java/sopt/jeolloga/domain/templestay/api/vo/TemplestayVO.java
  src/main/java/sopt/jeolloga/domain/templestay/core/Review.java
  src/main/java/sopt/jeolloga/domain/templestay/core/ReviewRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/Templestay.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/exception/FilteredTemplestayNotFoundException.java
  src/main/java/sopt/jeolloga/domain/templestay/core/exception/JsonFieldErrorException.java
  src/main/java/sopt/jeolloga/domain/templestay/core/exception/TemplestayCoreException.java
  src/main/java/sopt/jeolloga/domain/templestay/core/exception/TemplestayNotFoundException.java
  src/main/java/sopt/jeolloga/exception/ErrorCode.java
Labels: feat

#11 Feat/#issue review
  src/main/java/sopt/jeolloga/common/DataUtils.java
  src/main/java/sopt/jeolloga/domain/templestay/api/GlobalExceptionHandler.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/ReviewApiController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/ReviewController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/Reviewcontroller.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/PageReviewRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/ReviewApiDto.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/ReviewRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/ReviewService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/ReviewRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayRepository.java
  src/main/java/sopt/jeolloga/exception/ErrorCode.java
Labels: feat

#10 Feat/#2 filter
  build.gradle
  src/main/java/sopt/jeolloga/JeollogaApplication.java
  src/main/java/sopt/jeolloga/common/Filters.java
  src/main/java/sopt/jeolloga/config/JwtAuthenticationFilter.java
  src/main/java/sopt/jeolloga/config/JwtTokenProvider.java
  src/main/java/sopt/jeolloga/config/OAuth2LoginSuccessHandler.java
  src/main/java/sopt/jeolloga/config/SecurityConfig.java
  src/main/java/sopt/jeolloga/domain/member/login/controller/AuthController.java
  src/main/java/sopt/jeolloga/domain/member/login/controller/JwtTestController.java
  src/main/java/sopt/jeolloga/domain/member/login/controller/LoginController.java
  src/main/java/sopt/jeolloga/domain/member/login/controller/MemberController.java
  src/main/java/sopt/jeolloga/domain/member/login/dto/JwtResponse.java
  src/main/java/sopt/jeolloga/domain/member/login/repository/Member.java
  src/main/java/sopt/jeolloga/domain/member/login/repository/MemberRepository.java
  src/main/java/sopt/jeolloga/domain/member/login/service/AuthService.java
  src/main/java/sopt/jeolloga/domain/member/login/service/CustomOAuth2User.java
  src/main/java/sopt/jeolloga/domain/member/login/service/CustomOAuth2UserService.java
  src/main/java/sopt/jeolloga/domain/member/login/service/MemberService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/FilterController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/FilterCountRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/FilterListRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/FilterRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/PagingRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/ResetFilterRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/FilterService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/CategoryEntity.java
  src/main/java/sopt/jeolloga/domain/templestay/core/CategoryRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/ImageUrlEntity.java
  src/main/java/sopt/jeolloga/domain/templestay/core/ImageUrlRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayEntity.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayRepository.java
Labels: feat

#15 Feat/login
  src/main/java/sopt/jeolloga/common/Filters.java
  src/main/java/sopt/jeolloga/config/JwtAuthenticationFilter.java
  src/main/java/sopt/jeolloga/config/OAuth2LoginSuccessHandler.java
  src/main/java/sopt/jeolloga/config/SecurityConfig.java
  src/main/java/sopt/jeolloga/domain/member/CustomAuthenticationBaseException.java
  src/main/java/sopt/jeolloga/domain/member/api/CustomAuthenticationExceptionHandler.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/AuthController.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/LoginController.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/MemberController.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/authTestContoller.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/MemberNameRes.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/MemberReq.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/MemberRes.java
  src/main/java/sopt/jeolloga/domain/member/api/service/AuthService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/CustomOAuth2User.java
  src/main/java/sopt/jeolloga/domain/member/api/service/CustomOAuth2UserService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/MemberService.java
  src/main/java/sopt/jeolloga/domain/member/api/utils/CustomAuthenticationEntryPoint.java
  src/main/java/sopt/jeolloga/domain/member/api/utils/JwtTokenProvider.java
  src/main/java/sopt/jeolloga/domain/member/core/Member.java
  src/main/java/sopt/jeolloga/domain/member/core/MemberRepository.java
  src/main/java/sopt/jeolloga/domain/member/core/exception/CustomAuthenticationCoreException.java
  src/main/java/sopt/jeolloga/domain/member/core/exception/InvalidAccessTokenException.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/FilterController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/PageTemplesayRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/FilterService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/CategoryEntity.java
  src/main/java/sopt/jeolloga/domain/templestay/core/CategoryRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayRepository.java
  src/main/java/sopt/jeolloga/domain/wishlist/api/service/WishlistService.java
  src/main/java/sopt/jeolloga/domain/wishlist/core/Wishlist.java
  src/main/java/sopt/jeolloga/domain/wishlist/core/WishlistRepository.java
  src/main/java/sopt/jeolloga/exception/ErrorCode.java
  src/main/resources/application.yaml
  src/main/resources/static/kakao_login_medium_narrow.png
  src/main/resources/template/login.html
Labels: feat

#13 Feat/#issue templestay detail
  src/main/java/sopt/jeolloga/common/DataUtils.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/ReviewController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestayController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestayImageController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayDetailRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayImgRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestayImageService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestayService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayImage.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayImageRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/UrlRepository.java
  src/main/java/sopt/jeolloga/domain/wishlist/core/WishlistRepository.java
Labels: feat

#23 Feat/#issue ranking
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestayRankingController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayRankingListRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayRankingRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestayRankingService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayRepository.java
Labels: feat

#28 [feat] 템플스테이 상세뷰에 상세 주소 추가
  src/main/java/sopt/jeolloga/common/DataUtils.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayDetailRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestayService.java
Labels: feat

#29 [feat] DTO 변경
  src/main/java/sopt/jeolloga/domain/member/api/controller/UserSearchController.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/DeleteSearchReq.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/SearchListRes.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/SearchRes.java
  src/main/java/sopt/jeolloga/domain/member/api/service/SearchService.java
  src/main/java/sopt/jeolloga/domain/member/core/Search.java
  src/main/java/sopt/jeolloga/domain/member/core/SearchRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestaySearchController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestaySearchReq.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
Labels: feat

#31 [refactor] api 호출시 parameter key 값 조정
  src/main/java/sopt/jeolloga/domain/member/api/controller/AuthController.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/MemberController.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/MemberDetailRes.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/MemberReq.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/MemberRes.java
  src/main/java/sopt/jeolloga/domain/member/api/service/CustomOAuth2UserService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/MemberService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/TokenService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/FilterController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayDetailRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayRes.java
  src/main/resources/static/kakao_login_medium_narrow.png
  src/main/resources/template/login.html
Labels: refactor

#32 [refactor] @RequestParam 및 @RequestBody 로 응답 변경
  src/main/java/sopt/jeolloga/domain/member/api/controller/UserSearchController.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/DeleteSearchReq.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/MemberIdReq.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/SearchRes.java
  src/main/java/sopt/jeolloga/domain/member/core/SearchRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/ReviewController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestayController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestayImageController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestayRankingController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestaySearchController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/PageReviewRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestaySearchReq.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestaySearchRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestayService.java
  src/main/java/sopt/jeolloga/domain/wishlist/api/controller/WishlistController.java
  src/main/java/sopt/jeolloga/domain/wishlist/api/dto/WishlistReq.java
Labels: refactor

#33 [refactor] api 호출시 parameter key 값 조정 추가
  src/main/java/sopt/jeolloga/common/Filters.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/ResetFilterRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayImgRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayRankingRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/FilterService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
  src/main/java/sopt/jeolloga/domain/wishlist/api/dto/WishlistTemplestayRes.java
  src/main/java/sopt/jeolloga/domain/wishlist/api/service/WishlistService.java
Labels: refactor

#37 [fix] img_Url가져오는것을 url테이블에서 templestay_image로 변경
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestayRankingService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayImage.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayImageRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/UrlRepository.java
  src/main/java/sopt/jeolloga/domain/wishlist/api/service/WishlistService.java
Labels: fix

#36 [feat] kakao login, logout 구현
  src/main/java/sopt/jeolloga/config/OAuth2LoginFailureHandler.java
  src/main/java/sopt/jeolloga/config/OAuth2LoginSuccessHandler.java
  src/main/java/sopt/jeolloga/config/RedisConfig.java
  src/main/java/sopt/jeolloga/config/SecurityConfig.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/AuthController.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/OAuthController.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/authTestContoller.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/KakaoTokenRes.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/KakaoUserInfoRes.java
  src/main/java/sopt/jeolloga/domain/member/api/service/AuthService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/CustomOAuth2UserService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/MemberService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/OAuthService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/TokenService.java
  src/main/java/sopt/jeolloga/domain/member/api/utils/CustomAuthenticationEntryPoint.java
  src/main/java/sopt/jeolloga/domain/member/api/utils/JwtTokenProvider.java
  src/main/java/sopt/jeolloga/domain/member/core/Member.java
  src/main/java/sopt/jeolloga/domain/member/core/RefreshToken.java
  src/main/java/sopt/jeolloga/domain/member/core/RefreshTokenRepository.java
  src/main/java/sopt/jeolloga/domain/member/core/Token.java
  src/main/resources/static/kakao_login_medium_narrow.png
  src/main/resources/templates/login.html
Labels: feat

#39 Feat/#issue temple search
  src/main/java/sopt/jeolloga/domain/templestay/api/TemplestayGlobalExceptionHandler.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestaySearchController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayFilterReq.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestaySearchRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/FilterService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayImageRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/core/exception/InvalidFilterException.java
Labels: bug, feat

#40 [fix] templestay filter 및 search 수정
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestaySearchController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/PageTemplestaySearchRes.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
Labels: fix

#44 Feat/#issue cors config
  src/main/java/sopt/jeolloga/config/CorsConfig.java
  src/main/java/sopt/jeolloga/config/SecurityConfig.java
  src/main/java/sopt/jeolloga/domain/member/api/dto/MemberReq.java
  src/main/java/sopt/jeolloga/domain/member/api/service/MemberService.java
Labels: feat

#45 [fix] 빈 문자열일 때 예외 제외 하고 검색결과 반환
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
Labels: fix

#47 Feat/#issue search with filter
  src/main/java/sopt/jeolloga/common/Filters.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/FilterController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestaySearchController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/dto/TemplestayFilterReqTemp.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/FilterService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayRepository.java
Labels: feat

#50 [fix] filter 관련 type conversion 오류 해결
  src/main/java/sopt/jeolloga/common/Filters.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/FilterService.java
Labels: fix

#51 [fix] 최근검색어 목록 10개 반환 오류수정
  src/main/java/sopt/jeolloga/domain/member/core/SearchRepository.java
Labels: fix

#54 [fix] 리뷰 이미지 url 변경
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/ImageProxyController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/ReviewService.java
Labels: fix

#55 [chore] TOP3 랭킹 변경
  .gitignore
  data/crawling/AdressCrawling.py
  data/db_config.yaml
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestayRankingService.java
Labels: chore

#59 Refactor/#issue token
  src/main/java/sopt/jeolloga/domain/member/api/controller/OAuthController.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/TestConrtoller.java
  src/main/java/sopt/jeolloga/domain/member/api/service/MemberService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/OAuthService.java
  src/main/java/sopt/jeolloga/domain/member/api/service/TokenService.java
  src/main/java/sopt/jeolloga/domain/member/api/utils/JwtTokenProvider.java
  src/main/java/sopt/jeolloga/domain/member/core/RefreshToken.java
Labels: refactor

#57 [refactor] login시 redirect-uri 전달 받기
  src/main/java/sopt/jeolloga/domain/member/api/controller/OAuthController.java
  src/main/java/sopt/jeolloga/domain/member/api/service/OAuthService.java
Labels: refactor

#60 [fix] price 필터링 추가
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestaySearchController.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
  src/main/java/sopt/jeolloga/domain/templestay/core/TemplestayRepository.java
Labels: fix

#62 [fix] cors 설정 변경
  src/main/java/sopt/jeolloga/config/CorsConfig.java
  src/main/java/sopt/jeolloga/domain/member/api/controller/TestController.java
  src/main/java/sopt/jeolloga/domain/member/api/service/OAuthService.java
  src/main/java/sopt/jeolloga/domain/templestay/api/controller/TemplestayRankingController.java
  src/main/java/sopt/jeolloga/domain/wishlist/core/WishlistRepository.java
Labels: fix

#64 [fix] 검색어 목록 반환 수정
  src/main/java/sopt/jeolloga/domain/member/core/SearchRepository.java
  src/main/java/sopt/jeolloga/domain/templestay/api/service/TemplestaySearchService.java
Labels: bug
